apiVersion: v1
kind: PersistentVolume
metadata:
  name: mayuran-local-storage-node1-001
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mayuran-local-storage-class
  local:
    path: /mayuran/data/001
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1